In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
lr = cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)
lr

c:\Users\pilot\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [15]:
np.average(lr)

np.float64(0.9733333333333333)

In [17]:
svm = cross_val_score(SVC(), iris.data, iris.target, cv=3)
svm

array([0.96, 0.98, 0.94])

In [18]:
np.average(svm)

np.float64(0.96)

In [20]:
dtree = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
dtree

array([0.98, 0.92, 0.98])

In [22]:
np.average(dtree)

np.float64(0.96)

In [24]:
rf = cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)
rf

array([0.98, 0.94, 0.96])

In [25]:
np.average(rf)

np.float64(0.96)